export enum UserActions {
    FETCH_POSTS = 'FETCH_POSTS',
    SET_OPENED_USER = 'SET_OPENED_USER',
}

export enum PostActions {
    FETCH_FILTERED_BY_USER_POSTS = 'FETCH_FILTERED_BY_USER_POSTS',
    FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID',
    IS_LOADING_COMMENTS = 'IS_LOADING_COMMENTS',
}
