export enum UserActions {
    FETCH_POSTS = 'FETCH_POSTS',
}

export enum PostActions {
    FETCH_FILTERED_BY_USER_POSTS = 'FETCH_FILTERED_BY_USER_POSTS',
    FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID',
}
