export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_FILTERED_POSTS = 'FETCH_FILTERED_POSTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_OPENED_USER = 'FETCH_OPENED_USER';
